init scripts and additional features

diff --git a/service/init/logmind-shipper b/service/init/logmind-shipper
--- a/service/init/logmind-shipper
+++ b/service/init/logmind-shipper
@@ -1,101 +1,107 @@
-#! /bin/bash
+#!/bin/bash
+
 ### BEGIN INIT INFO
-# Provides:          logmind-redis
+# Provides:          logmind-shipper
 # Required-Start:    $all
 # Required-Stop:     $all
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: Starts logmind-redis
-# Description:       Starts logmind-redis using start-stop-daemon
+# Short-Description: Starts logmind-shipper
+# Description:       Starts logmind-shipper as a daemon
 ### END INIT INFO
 
-# You may need to change these
-USER=logmind          # the user you used to run the redis
+# absolute path to executable binary
+progpath=$(which java)
 
-### BEGIN user-configurable settings
-NAME=logmind-redis
-DESC=Logmind redis
-REDIS_HOME=/usr/local/logmind/redis
-PID_FILE=$REDIS_HOME/$NAME.pid
-LOG_DIR=$REDIS_HOME/logs
-DATA_DIR=$REDIS_HOME/data
-CONFIG_FILE=$ES_HOME/config/redis.conf
-WORK_DIR=/tmp/$NAME
-DAEMON=$REDIS_HOME/bin/redis-server
-DAEMON_OPTS="$CONFIG_FILE"
-### END user-configurable settings
+# arguments to script
+opts='-jar /usr/local/logmind/sixthsense/logstash.jar agent -f /usr/local/logmind/sixthsense/config/shipper.conf'
 
+# binary program name
+prog='logmind-shipper'
 
-# Pull in RHEL/CentOS-specific functionality (daemon, killproc) if available.
-if [ -x /etc/init.d/functions ]; then source /etc/init.d/functions; fi
+# logfile 
+logfile=/usr/local/logmind/sixthsense/$prog.log
 
-# Exit if the executable is missing.
-if [ ! -x $DAEMON ]; then
-  echo 'Could not find redis executable!'
-  exit 0
-fi
+# pid file
+pidfile="/var/run/${prog}.pid"
 
-# Exit if any command (outside a conditional) fails.
-set -e
+# make sure full path to executable binary is found
+! [ -x $progpath ] && echo "$progpath: executable not found" && exit 1
 
+start() {
+  # see if running
+  if [ -f $pidfile ]; then 
+    local pid=$(cat $pidfile)
 
-case "$1" in
+    if [ -d "/proc/$pid" ]; then
+      echo "$prog (pid $pid) is already running"
+      return 0
+    fi
+  fi
+  
+  printf "%-50s%s" "Starting $prog: " ''
+  
+  # run the program in the background
+  $progpath $opts > $logfile 2>&1 &
+
+  # save pid to file
+  local pid=$!
+  echo $pid > $pidfile
+  
+  if [ -d "/proc/$pid" ]; then
+    echo "started"
+  else
+    echo "failed"
+  fi
+}
+
+stop() {
+  if [ -f $pidfile ]; then 
+    local pid=$(cat $pidfile)
+	if [ -d "/proc/$pid" ]; then
+	  printf "%-50s%s" "Stopping $prog (pid $pid): " ''
+      kill -TERM $pid
+	  echo stopped
+	  rm -f $pidfile
+	  return 0
+    fi
+  fi
+  
+  echo "$prog not running"
+}
+
+status() {
+  # see if running
+  if [ -f $pidfile ]; then 
+    local pid=$(cat $pidfile)
+
+    if [ -f "/proc/$pid/exe" ]; then
+      echo "$prog (pid $pid) is running"
+	  return 0
+    fi
+  fi
+  
+  echo "$prog is stopped"
+}
+
+case $1 in
   start)
-    echo -n "Starting $DESC: "
-    mkdir -p $LOG_DIR $DATA_DIR $WORK_DIR
-    chown -R $USER:$USER $LOG_DIR $DATA_DIR $WORK_DIR
-    if type -p start-stop-daemon > /dev/null; then
-      start-stop-daemon --start --pidfile $PID_FILE --user $USER --chuid $USER --startas $DAEMON -- $DAEMON_OPTS
-    else
-      runuser -s /bin/bash $USER -c "$DAEMON $DAEMON_OPTS"
-    fi
-    if [ $? == 0 ]
-    then
-        echo "started."
-    else
-        echo "failed."
-    fi
+    start
     ;;
   stop)
-    if [ ! -e $PID_FILE ]; then
-      echo "$DESC not running (no PID file)"
-    else
-      echo -n "Stopping $DESC: "
-      if type -p start-stop-daemon > /dev/null; then
-        start-stop-daemon --stop --pidfile $PID_FILE
-      else
-        kill $(cat $PID_FILE)
-        rm $PID_FILE
-      fi
-      if [ $? == 0 ]
-      then
-          echo "stopped."
-      else
-          echo "failed."
-      fi
-    fi
-    ;;
-  restart|force-reload)
-    ${0} stop
-    sleep 0.5
-    ${0} start
+    stop
     ;;
   status)
-    if [ ! -f $PID_FILE ]; then
-      echo "$DESC not running"
-    else
-      if ps auxw | grep $(cat $PID_FILE) | grep -v grep > /dev/null; then
-        echo "running on pid $(cat $PID_FILE)"
-      else
-        echo 'not running (but PID file exists)'
-      fi
-    fi
+    status
+    ;;
+  restart)
+    stop
+    sleep 1
+    start
     ;;
   *)
-    N=/etc/init.d/$NAME
-    echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
+    echo "Usage: $0 {start|stop|status|restart}"
     exit 1
-    ;;
 esac
 
-exit 0
+exit $?
